---
os: linux
dist: xenial
language: python
python:
  - 3.7
cache: pip
services:
  - docker
env:
  - ANSIBLE=2.7
  - ANSIBLE=2.8
  - ANSIBLE=2.9
  - ANSIBLE=2.10
install: 
  - pip install molecule docker
script:
  - molecule test --all --destroy always
