---
- name: Create the beanstalkd_exporter group
  group:
    name: "{{ beanstalkd_exporter_system_group }}"
    state: present
    system: true
  when: beanstalkd_exporter_system_group != "root"

- name: Create the beanstalkd_exporter user
  user:
    name: "{{ beanstalkd_exporter_system_user }}"
    groups: "{{ beanstalkd_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when: beanstalkd_exporter_system_user != "root"

- block:
    - name: Download beanstalkd_exporter binary to local folder
      become: false
      get_url:
        url: "https://github.com/messagebird/beanstalkd_exporter/releases/download/{{ beanstalkd_exporter_version }}/beanstalkd_exporter-{{ beanstalkd_exporter_version }}.linux-{{ go_arch }}"
        dest: "/tmp/beanstalkd_exporter-{{ beanstalkd_exporter_version }}.linux-{{ go_arch }}"
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Propagate beanstalkd_exporter binaries
      copy:
        src: "/tmp/beanstalkd_exporter-{{ beanstalkd_exporter_version }}.linux-{{ go_arch }}"
        dest: "{{ beanstalkd_exporter_binary_install_dir }}/beanstalkd_exporter"
        mode: 0755
        owner: root
        group: root
      notify: restart beanstalkd_exporter
      when: not ansible_check_mode
  when: beanstalkd_exporter_binary_local_dir | length == 0

- name: propagate locally distributed beanstalkd_exporter binary
  copy:
    src: "{{ beanstalkd_exporter_binary_local_dir }}/beanstalkd_exporter"
    dest: "{{ beanstalkd_exporter_binary_install_dir }}/beanstalkd_exporter"
    mode: 0755
    owner: root
    group: root
  when: beanstalkd_exporter_binary_local_dir | length > 0
  notify: restart beanstalkd_exporter
