---
- import_tasks: preflight.yml
  tags:
    - beanstalkd_exporter_install
    - beanstalkd_exporter_configure
    - beanstalkd_exporter_run

- import_tasks: install.yml
  become: true
  when:
    ( not __beanstalkd_exporter_is_installed.stat.exists ) or
    ( __beanstalkd_exporter_current_version_output.stderr_lines[0].split(" ")[2] != beanstalkd_exporter_version ) or
    ( beanstalkd_exporter_binary_local_dir | length > 0 )
  tags:
    - beanstalkd_exporter_install

- import_tasks: configure.yml
  become: true
  tags:
    - beanstalkd_exporter_configure

- name: Ensure Beanstalkd Exporter is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: beanstalkd_exporter
    enabled: true
    state: started
  tags:
    - beanstalkd_exporter_run
